const footerMenu = [
  {
    title: 'services',
    items: [
      'Domain Marketplace',
      'Ultra Premium Marketplace',
      'Premium Domains For Sale',
      'Crowdsource Naming',
      'Brandable Domains',
      'Short Domains',
      '3 Letter Domains',
      '4 Letter Domains',
      '5 Letter Domains',
      '6 Letter Domains',
      '7 Letter Domains',
      'One Word Domains',
      'Brand Identity Design',
      'Agency Services',
      'Logo Contests',
      'Tagline Contests',
      'Trademark Filing Service',
      'Audience Test',
    ],
  },
  {
    title: 'tools',
    items: [
      'Business Name Generator',
      'Domain Name Generator',
      'Domain Appraisal',
      'How to Name Your Business',
      'Free Trademark Checker',
      'Branding Blog',
      'Business Naming eBook',
      'Startup Toolkit',
      'Startup Name Generator',
      'Band Name Generator',
      'Blog Name Generator',
      'YouTube Name Generator',
      'Domain Extensions',
      'Build a Brand',
    ],
  },
  {
    title: 'sellers',
    items: [
      'Become a Seller',
      'Domain Selling Info',
      'Ultra Premium Seller Info',
      'Discussion Forum',
    ],
  },
  {
    title: 'atom',
    items: [
      'About',
      'Contact',
      'How It Works',
      'Testimonials',
      'Our Work',
      'Help & FAQs',
      'AtomConnect',
      'AtomRadar',
    ],
  },
  {
    title: 'creatives',
    items: [
      'Become a Creative',
      'Creative FAQs',
      'Active Contests',
      'Recent Winners',
      'Discussion Forum',
    ],
  },
  {
    title: 'legal',
    items: ['Terms of Service', 'Privacy Policy', 'Cookie Policy'],
  },
];
export default footerMenu;
